name: my-first-gh-workflow  # workflow name
on: [push]                  # triggering event
jobs:                       # list of jobs
  say-hello:             #job name
    runs-on: ubuntu-latest
    steps:                  #list of steps
      - name: Checkout the code
        uses: actions/checkout@v2
      - run: tar -czf myrepo.tgz .
        name: Build the code   
      - run: tar -tzvf myrepo.tgz
        name: Test the artifact
